- docs/data-sources/cce_cluster.md
- docs/data-sources/cce_node.md
- docs/data-sources/images_image.md
- docs/data-sources/networking_port.md
- docs/data-sources/networking_secgroup.md
- docs/resources/cce_cluster.md
- docs/resources/cce_node.md
- docs/resources/compute_eip_associate.md
- docs/resources/compute_instance.md
- docs/resources/compute_interface_attach.md
- docs/resources/compute_keypair.md
- docs/resources/compute_servergroup.md
- docs/resources/compute_volume_attach.md
- docs/resources/vpc_bandwidth.md
- sbercloud/data_source_sbercloud_cce_cluster_v3_test.go
- sbercloud/data_source_sbercloud_cce_node_v3_test.go
- sbercloud/provider.go
- sbercloud/resource_sbercloud_cce_cluster_v3_test.go
- sbercloud/resource_sbercloud_cce_node_v3_test.go
- vendor/modules.txt
The following resources and data_sources were added:
data_source_sbercloud_cce_cluster
data_source_sbercloud_cce_node
resource_sbercloud_cce_cluster
resource_sbercloud_cce_node_v3
```bash
make testacc TEST='./sbercloud' TESTARGS='-run TestAccCCE'
TF_ACC=1 go test ./sbercloud -v -run TestAccCCE -timeout 360m
=== RUN   TestAccCCEClusterV3DataSource_basic
=== PAUSE TestAccCCEClusterV3DataSource_basic
=== RUN   TestAccCCENodeV3DataSource_basic
=== PAUSE TestAccCCENodeV3DataSource_basic
=== RUN   TestAccCCEClusterV3_basic
=== PAUSE TestAccCCEClusterV3_basic
=== RUN   TestAccCCEClusterV3_withEip
=== PAUSE TestAccCCEClusterV3_withEip
=== RUN   TestAccCCEClusterV3_withEpsId
=== PAUSE TestAccCCEClusterV3_withEpsId
=== RUN …
```
> add cce resources and data_sources

- docs/resources/as_configuration.md
- docs/resources/as_group.md
- docs/resources/as_policy.md
- sbercloud/provider.go
- sbercloud/resource_sbercloud_as_configuration_v1_test.go
- sbercloud/resource_sbercloud_as_group_v1_test.go
- sbercloud/resource_sbercloud_as_policy_v1_test.go
The fllowing resources were added:
resource_sbercloud_as_configuration
resource_sbercloud_as_group
resource_sbercloud_as_policy
```bash
make testacc TEST='./sbercloud' TESTARGS='-run TestAccAS'
TF_ACC=1 go test ./sbercloud -v -run TestAccAS -timeout 360m
=== RUN   TestAccASV1Configuration_basic
=== PAUSE TestAccASV1Configuration_basic
=== RUN   TestAccASV1Group_basic
=== PAUSE TestAccASV1Group_basic
=== RUN   TestAccASV1Policy_basic
=== PAUSE TestAccASV1Policy_basic
=== CONT  TestAccASV1Configuration_basic
=== CONT  TestAccASV1Policy_basic
=== CONT  TestAccASV1Group_basic
--- PASS: TestAccASV1Configuration_basic (120.35s)
--- PASS: TestAccASV1Policy_basic (154.24s)
--- PASS: TestAccASV1Group_basic (223.26s)
PASS
ok …
```
> add AS resources

- sbercloud/resource_sbercloud_nat_gateway_test.go
- sbercloud/resource_sbercloud_nat_snat_rule_test.go
This PR fixes some NAT acceptance tests and adds missed test with enterprise project id.
Now all NAT acceptance tests are done successfully:
```
make testacc TEST='./sbercloud' TESTARGS='-run TestAccNat'
TF_ACC=1 go test ./sbercloud -v -run TestAccNat -timeout 360m -parallel=4
=== RUN   TestAccNatGatewayDataSource_basic
=== PAUSE TestAccNatGatewayDataSource_basic
=== RUN   TestAccNatDnat_basic
=== PAUSE TestAccNatDnat_basic
=== RUN   TestAccNatDnat_protocol
=== PAUSE TestAccNatDnat_protocol
=== RUN   TestAccNatGateway_basic
=== PAUSE TestAccNatGateway_basic
=== RUN   TestAccNatGateway_withEpsId
=== PAUSE TestAccNatGateway_withEpsId
=== RUN   TestAccNatSnatRule_basic
=== PAUSE TestAccNatSnatRule_basic
=== CONT …
```
> Fix NAT acceptance tests

- sbercloud/data_source_sbercloud_vpc_subnet_test.go
- sbercloud/data_source_sbercloud_vpc_test.go
- sbercloud/resource_sbercloud_vpc_test.go
This PR fixes some VPC acceptance tests and adds missed one.
For now all VPC tests are done well:
```
make testacc TEST='./sbercloud' TESTARGS='-run TestAccVpc'
TF_ACC=1 go test ./sbercloud -v -run TestAccVpc -timeout 360m -parallel=4
=== RUN   TestAccVpcRouteV2DataSource_basic
=== PAUSE TestAccVpcRouteV2DataSource_basic
=== RUN   TestAccVpcSubnetIdsV2DataSource_basic
=== PAUSE TestAccVpcSubnetIdsV2DataSource_basic
=== RUN   TestAccVpcSubnetV1DataSource_basic
=== PAUSE TestAccVpcSubnetV1DataSource_basic
=== RUN   TestAccVpcV1DataSource_basic
=== PAUSE TestAccVpcV1DataSource_basic
=== RUN   TestAccVpcBandWidthV2_basic
=== PAUSE TestAccVpcBandWidthV2_basic
=== RUN   TestAccVpcBandWidthV2_WithEpsId
=== PAUSE …
```
> Fix VPC acceptance tests

- sbercloud/provider_test.go
- sbercloud/resource_sbercloud_obs_bucket_object_test.go
- sbercloud/resource_sbercloud_obs_bucket_policy_test.go
- sbercloud/resource_sbercloud_obs_bucket_test.go
This PR fixes some OBS acceptance tests and adds missed one.
Now all OBS acceptance tests are done successfully:
```
make testacc TEST='./sbercloud' TESTARGS='-run TestAccObs'
TF_ACC=1 go test ./sbercloud -v -run TestAccObs -timeout 360m -parallel=4
=== RUN   TestAccObsBucketObject_source
=== PAUSE TestAccObsBucketObject_source
=== RUN   TestAccObsBucketObject_content
=== PAUSE TestAccObsBucketObject_content
=== RUN   TestAccObsBucketPolicy_basic
=== PAUSE TestAccObsBucketPolicy_basic
=== RUN   TestAccObsBucketPolicy_update
=== PAUSE TestAccObsBucketPolicy_update
=== RUN   TestAccObsBucketPolicy_s3
=== PAUSE TestAccObsBucketPolicy_s3
=== RUN   TestAccObsBucket_basic
=== PAUSE TestAccObsBucket_basic
=== RUN …
```
> Fix OBS acceptance tests

- docs/resources/network_acl.md
- docs/resources/network_acl_rule.md
- sbercloud/provider.go
- sbercloud/resource_sbercloud_network_acl_rule_test.go
- sbercloud/resource_sbercloud_network_acl_test.go
This PR adds 2 objects:
**Resources**
sbercloud_network_acl
sbercloud_network_acl_rule
This closes #38 
All related acceptance tests are done:
```
make testacc TEST='./sbercloud' TESTARGS='-run TestAccNetworkACL'
TF_ACC=1 go test ./sbercloud -v -run TestAccNetworkACL -timeout 360m -parallel=4
=== RUN   TestAccNetworkACLRule_basic
=== PAUSE TestAccNetworkACLRule_basic
=== RUN   TestAccNetworkACLRule_anyProtocol
=== PAUSE TestAccNetworkACLRule_anyProtocol
=== RUN   TestAccNetworkACL_basic
=== PAUSE TestAccNetworkACL_basic
=== RUN   TestAccNetworkACL_no_subnets
=== PAUSE TestAccNetworkACL_no_subnets
=== RUN   TestAccNetworkACL_remove
=== PAUSE TestAccNetworkACL_remove
=== CONT  TestAccNetworkACLRule_basic
=== CONT …
```
> Add network ACL resources

- .github/workflows/release.yml
Goreleaser's GitHub action disables builds for darwin/arm64 with go prior 1.16 because old go versions consider darwin/arm64 as iOS arch, not apple silicon. Update go to 1.16 allowed goreleaser to prepare darwin/arm64 artifacts.
https://goreleaser.com/deprecations/#builds-for-darwinarm64
> Update go to 1.16 in setup-go action to enable darwin/arm64 builds

- docs/resources/css_cluster.md
- sbercloud/provider.go
- sbercloud/resource_sbercloud_css_cluster_v1_test.go
This PR adds `sbercloud_css_cluster` resource.
This closes #78 
```
make testacc TEST='./sbercloud' TESTARGS='-run TestAccCss'
TF_ACC=1 go test ./sbercloud -v -run TestAccCss -timeout 360m -parallel=4
=== RUN   TestAccCssClusterV1_basic
=== PAUSE TestAccCssClusterV1_basic
=== RUN   TestAccCssClusterV1_security
=== PAUSE TestAccCssClusterV1_security
=== CONT  TestAccCssClusterV1_basic
=== CONT  TestAccCssClusterV1_security
--- PASS: TestAccCssClusterV1_basic (954.62s)
--- PASS: TestAccCssClusterV1_security (996.64s)
PASS
ok      github.com/sbercloud-terraform/terraform-provider-sbercloud/sbercloud   997.141s
```
> Add CSS cluster resource

- docs/resources/ces_alarmrule.md
- sbercloud/provider.go
- sbercloud/resource_sbercloud_ces_alarmrule_test.go
This PR adds `sbercloud_ces_alarmrule` resource.
This closes #77
```
make testacc TEST='./sbercloud' TESTARGS='-run TestAccCES'
TF_ACC=1 go test ./sbercloud -v -run TestAccCES -timeout 360m -parallel=4
=== RUN   TestAccCESAlarmRule_basic
=== PAUSE TestAccCESAlarmRule_basic
=== CONT  TestAccCESAlarmRule_basic
--- PASS: TestAccCESAlarmRule_basic (140.23s)
PASS
ok      github.com/sbercloud-terraform/terraform-provider-sbercloud/sbercloud   140.611s
```
> Add CES alarmrule resource

- docs/resources/ges_graph.md
- sbercloud/provider.go
- sbercloud/resource_sbercloud_ges_graph_test.go
This PR adds `sbercloud_ges_graph` resource.
This closes #75 
```
make testacc TEST='./sbercloud' TESTARGS='-run TestAccGes'
TF_ACC=1 go test ./sbercloud -v -run TestAccGes -timeout 360m -parallel=4
=== RUN   TestAccGesGraphV1_basic
=== PAUSE TestAccGesGraphV1_basic
=== CONT  TestAccGesGraphV1_basic
--- PASS: TestAccGesGraphV1_basic (996.96s)
PASS
ok      github.com/sbercloud-terraform/terraform-provider-sbercloud/sbercloud   997.484s
```
> Add GES Graph resource

- docs/data-sources/cbr_vaults.md
- docs/resources/cbr_policy.md
- docs/resources/cbr_vault.md
- sbercloud/cbr/data_source_sbercloud_cbr_vaults_test.go
- sbercloud/cbr/resource_sbercloud_cbr_policy_test.go
- sbercloud/cbr/resource_sbercloud_cbr_vault_test.go
- sbercloud/provider.go
This PR adds 3 objects:
**Data Sources**
sbercloud_cbr_vaults
**Resources**
sbercloud_cbr_policy
sbercloud_cbr_vault
This closes #117 
All CBR acceptance tests are done well:
```
make testacc TEST='./sbercloud/cbr' TESTARGS='-run TestAcc'
TF_ACC=1 go test ./sbercloud/cbr -v -run TestAcc -timeout 360m -parallel=4
=== RUN   TestAccCbrVaultsV3_BasicServer
=== PAUSE TestAccCbrVaultsV3_BasicServer
=== RUN   TestAccCbrVaultsV3_BasicVolume
=== PAUSE TestAccCbrVaultsV3_BasicVolume
=== RUN   TestAccCbrVaultsV3_BasicTurbo
=== PAUSE TestAccCbrVaultsV3_BasicTurbo
=== RUN   TestAccCBRV3Policy_basic
=== PAUSE TestAccCBRV3Policy_basic
=== RUN   TestAccCBRV3Vault_BasicServer
=== PAUSE TestAccCBRV3Vault_BasicServer
=== RUN …
```
> feat(CBR): add new objects

- docs/data-sources/enterprise_project.md
- docs/resources/enterprise_project.md
- sbercloud/eps/data_source_sbercloud_enterprise_project_test.go
- sbercloud/eps/resource_sbercloud_enterprise_project_test.go
- sbercloud/provider.go
This PR adds 2 objects:
**Data Sources**
sbercloud_enterprise_project
**Resources**
sbercloud_enterprise_project
This closes #119 
All EPS acceptance tests are done:
```
make testacc TEST='./sbercloud/eps' TESTARGS='-run TestAccEnterpriseProject'
TF_ACC=1 go test ./sbercloud/eps -v -run TestAccEnterpriseProject -timeout 360m -parallel=4
=== RUN   TestAccEnterpriseProjectDataSource_basic
=== PAUSE TestAccEnterpriseProjectDataSource_basic
=== RUN   TestAccEnterpriseProject_basic
=== PAUSE TestAccEnterpriseProject_basic
=== CONT  TestAccEnterpriseProjectDataSource_basic
=== CONT  TestAccEnterpriseProject_basic
--- PASS: TestAccEnterpriseProjectDataSource_basic (7.40s)
--- PASS: TestAccEnterpriseProject_basic (15.46s)
PASS
ok …
```
> feat(EPS): add new objects

- sbercloud/provider.go
- sbercloud/vpc/resource_sbercloud_vpc_route_table_route_test.go
This PR fixes `sbercloud_vpc_route` resource version with tests.
Related acceptance test is done successfully:
```
make testacc TEST='./sbercloud/vpc' TESTARGS='-run TestAccVpcRTBRoute'
TF_ACC=1 go test ./sbercloud/vpc -v -run TestAccVpcRTBRoute -timeout 360m -parallel=4
=== RUN   TestAccVpcRTBRoute_basic
=== PAUSE TestAccVpcRTBRoute_basic
=== CONT  TestAccVpcRTBRoute_basic
--- PASS: TestAccVpcRTBRoute_basic (41.62s)
PASS
ok      github.com/sbercloud-terraform/terraform-provider-sbercloud/sbercloud/vpc       41.966s
```
> fix(VPC): update vpc route resource

- docs/resources/identity_project.md
- sbercloud/iam/resource_sbercloud_identity_project_test.go
- sbercloud/provider.go
This PR adds `sbercloud_identity_project` resource.
This closes #105 
Related acceptance test is completely done:
```
make testacc TEST='./sbercloud/iam' TESTARGS='-run TestAccIdentityV3Project_basic'
TF_ACC=1 go test ./sbercloud/iam -v -run TestAccIdentityV3Project_basic -timeout 360m -parallel=4
=== RUN   TestAccIdentityV3Project_basic
=== PAUSE TestAccIdentityV3Project_basic
=== CONT  TestAccIdentityV3Project_basic
--- PASS: TestAccIdentityV3Project_basic (12.77s)
PASS
ok      github.com/sbercloud-terraform/terraform-provider-sbercloud/sbercloud/iam       13.132s
```
> feat(IAM): add identity_project resource

- docs/resources/as_configuration.md
- docs/resources/cce_node.md
- docs/resources/compute_instance.md
- docs/resources/evs_snapshot.md
- docs/resources/evs_volume.md
This PR changes unsupported `SATA` on `SSD` disk type for some examples.
This closes #97
> fix(doc): update disk_type from `SATA` to `SSD` for some examples

- docs/resources/compute_instance.md
`system_disk_type` for ECS was already marked as required parameter, but was omitted from the examples.
This PR updates ECS doc examples with required params.
This closes: #115
> fix(doc): update ECS doc examples with required params

- docs/index.md
This PR updates provider documentation with `security_token` parameter.
> fix(doc): add `security_token` description to index page

- sbercloud/provider.go
- sbercloud/resource_sbercloud_compute_instance.go
- sbercloud/resource_sbercloud_compute_instance_test.go
- sbercloud/resource_sbercloud_compute_volume_attach_test.go
- sbercloud/resource_sbercloud_evs_volume_test.go
This PR fixes broken `sbercloud_compute_instance` resource.
It's a temporary measure, since the refactoring of secgroup objects in the latest release has led
to incompatibility with current version of sbercloud secgroup API.
This commit also fixes broken some acceptance tests.
This closes https://github.com/sbercloud-terraform/terraform-provider-sbercloud/issues/132
All related acceptance tests are done:
```
TF_ACC=1 go test ./sbercloud -v -run TestAccComputeV2Instance -timeout 360m -parallel=4
=== RUN   TestAccComputeV2Instance_basic
=== PAUSE TestAccComputeV2Instance_basic
=== RUN   TestAccComputeV2Instance_disks
=== PAUSE TestAccComputeV2Instance_disks
=== RUN   TestAccComputeV2Instance_tags
=== PAUSE …
```
> fix(ecs): restore compatibility with service API

- docs/data-sources/cce_addon_template.md
- docs/resources/cce_addon.md
- examples/cce/basic/cce-addon-templates.md
- sbercloud/data_source_sbercloud_cce_addon_template_test.go
- sbercloud/provider.go
- sbercloud/resource_sbercloud_cce_addon_v3_test.go
This PR adds 2 objects:
**Data Sources**
sbercloud_cce_addon_template
**Resources**
sbercloud_cce_addon
This closes  #43 
All related CCE Addon acceptance tests are done:
```
TF_ACC=1 go test ./sbercloud -v -run TestAccCCEAddon -timeout 360m -parallel=1
=== RUN   TestAccCCEAddonTemplateV3DataSource_basic
=== PAUSE TestAccCCEAddonTemplateV3DataSource_basic
=== RUN   TestAccCCEAddonV3_basic
=== PAUSE TestAccCCEAddonV3_basic
=== RUN   TestAccCCEAddonV3_values
=== PAUSE TestAccCCEAddonV3_values
=== CONT  TestAccCCEAddonTemplateV3DataSource_basic
--- PASS: TestAccCCEAddonTemplateV3DataSource_basic (364.89s)
=== CONT  TestAccCCEAddonV3_values
--- PASS: TestAccCCEAddonV3_values (714.48s)
=== CONT  TestAccCCEAddonV3_basic
--- PASS: …
```
> feat(CCE): add addon objects

- docs/resources/mapreduce_cluster.md
- docs/resources/mapreduce_job.md
- sbercloud/provider.go
- sbercloud/resource_sbercloud_mapreduce_cluster_test.go
- sbercloud/resource_sbercloud_mapreduce_job_test.go
This PR add 2 objects:
**Resources**
sbercloud_mapreduce_cluster
sbercloud_mapreduce_job
This closes #67
```
TF_ACC=1 go test ./sbercloud -v -run TestAccMrsMapReduce -timeout 360m -parallel=1
=== RUN   TestAccMrsMapReduceCluster_basic
=== PAUSE TestAccMrsMapReduceCluster_basic
=== RUN   TestAccMrsMapReduceJob_basic
=== PAUSE TestAccMrsMapReduceJob_basic
=== CONT  TestAccMrsMapReduceCluster_basic
--- PASS: TestAccMrsMapReduceCluster_basic (814.26s)
=== CONT  TestAccMrsMapReduceJob_basic
--- PASS: TestAccMrsMapReduceJob_basic (1130.63s)
PASS
ok      github.com/sbercloud-terraform/terraform-provider-sbercloud/sbercloud   1945.612s
```
> feat(MRS): add new resources

- docs/data-sources/cce_clusters.md
- docs/data-sources/cce_nodes.md
- docs/resources/cce_cluster.md
- docs/resources/cce_namespace.md
- docs/resources/cce_node.md
- docs/resources/cce_node_attach.md
- docs/resources/cce_node_pool.md
- docs/resources/cce_pvc.md
- sbercloud/cce/data_source_sbercloud_cce_addon_template_test.go
- sbercloud/cce/data_source_sbercloud_cce_cluster_test.go
- sbercloud/cce/data_source_sbercloud_cce_clusters_test.go
- sbercloud/cce/data_source_sbercloud_cce_node_pool_test.go
- sbercloud/cce/data_source_sbercloud_cce_node_test.go
- sbercloud/cce/data_source_sbercloud_cce_nodes_test.go
- sbercloud/cce/resource_sbercloud_cce_addon_test.go
- sbercloud/cce/resource_sbercloud_cce_cluster_test.go
- sbercloud/cce/resource_sbercloud_cce_namespace_test.go
- sbercloud/cce/resource_sbercloud_cce_node_attach_test.go
- sbercloud/cce/resource_sbercloud_cce_node_pool_test.go
- sbercloud/cce/resource_sbercloud_cce_node_test.go
- sbercloud/cce/resource_sbercloud_cce_pvc_test.go
- sbercloud/provider.go
This PR adds 5 objects:
**Data Sources**
sbercloud_cce_clusters
sbercloud_cce_nodes
**Resources**
sbercloud_cce_node_attach
sbercloud_cce_namespace
sbercloud_cce_pvc
Also this PR:
- Replaces all existing CCE tests to the separate directory
- Updates CCE docs
This closes #155
All CCE acceptance tests are done well:
```
TF_ACC=1 go test ./sbercloud/cce -v -run TestAccCCE -timeout 360m -parallel=1
=== RUN   TestAccCCEAddonTemplateV3DataSource_basic
=== PAUSE TestAccCCEAddonTemplateV3DataSource_basic
=== RUN   TestAccCCEClusterV3DataSource_basic
=== PAUSE TestAccCCEClusterV3DataSource_basic
=== RUN   TestAccCCEClustersDataSource_basic
=== PAUSE TestAccCCEClustersDataSource_basic
=== RUN   TestAccCCENodePoolV3DataSource_basic
=== PAUSE …
```
> Add new CCE objects

- docs/data-sources/compute_instance.md
- docs/data-sources/compute_instances.md
- sbercloud/data_source_sbercloud_compute_instance_test.go
- sbercloud/data_source_sbercloud_compute_instances_test.go
- sbercloud/provider.go
- sbercloud/resource_sbercloud_compute_instance_test.go
This PR adds 2 datasources:
sbercloud_compute_instance
sbercloud_compute_instances
This closes #148 
```
TF_ACC=1 go test ./sbercloud -v -run TestAccComputeInstanceDataSource -timeout 360m -parallel=1
=== RUN   TestAccComputeInstanceDataSource_basic
=== PAUSE TestAccComputeInstanceDataSource_basic
=== CONT  TestAccComputeInstanceDataSource_basic
--- PASS: TestAccComputeInstanceDataSource_basic (131.49s)
PASS
ok      github.com/sbercloud-terraform/terraform-provider-sbercloud/sbercloud
```
```
TF_ACC=1 go test ./sbercloud -v -run TestAccComputeInstancesDataSource -timeout 360m -parallel=1
=== RUN   TestAccComputeInstancesDataSource_basic
=== …
```
> feat(ECS): add new datasources

- docs/resources/network_acl.md
- docs/resources/network_acl_rule.md
This PR updates the documentation for the following resources:
sbercloud_network_acl
sbercloud_network_acl_rule
This closes #141
> docs(network-acl): update the documentation

- docs/resources/aom_service_discovery_rule.md
- sbercloud/aom/resource_sbercloud_aom_service_discovery_rule_test.go
- sbercloud/provider.go
This PR adds `sbercloud_aom_service_discovery_rule` resource
Related to #151
All related acceptance tests are done well:
```
TF_ACC=1 go test ./sbercloud/aom -v  -timeout 360m -parallel=1
=== RUN   TestAccAOMServiceDiscoveryRule_basic
=== PAUSE TestAccAOMServiceDiscoveryRule_basic
=== CONT  TestAccAOMServiceDiscoveryRule_basic
--- PASS: TestAccAOMServiceDiscoveryRule_basic (23.58s)
PASS
ok      github.com/sbercloud-terraform/terraform-provider-sbercloud/sbercloud/aom       24.146s
```
> feat(AOM): add service discovery rule resource
